const en = {
  nav: {
    services: "Services",
    pricing: "Pricing",
    method: "Method",
    work: "Work",
    audit: "Audit",
    seo: "SEO",
    contact: "Contact",
    cta: "Request an audit",
  },
  hero: {
    label: "Digital studio for architecture & interior design",
    headline: "Your work already feels premium. Your website should too.",
    sub: "FORMA COSTA creates refined websites, portfolio systems, and local SEO foundations for architecture and interior design studios on the Costa del Sol.",
    ctaPrimary: "Request a website audit",
    ctaSecondary: "See the method",
    proof: "Built for studios in Marbella, Estepona, Sotogrande, Benahavís and Málaga.",
  },
  problem: {
    heading: "Most studios lose trust before the first call.",
    body: "Architecture and interior design are visual businesses. When a website feels outdated, slow, generic, or hard to browse, the quality of the studio is judged before the visitor even sees the work properly.",
    cards: [
      { title: "Outdated first impression", desc: "Visitors judge the studio in under three seconds. A visual mismatch between real work and website erodes trust instantly." },
      { title: "Weak project storytelling", desc: "Projects deserve more than a gallery grid. Each piece of work should communicate scope, materials, challenge, and result." },
      { title: "Poor mobile experience", desc: "Most inquiries start on a phone. A studio website that collapses on mobile sends the wrong signal immediately." },
      { title: "No clear enquiry path", desc: "If finding the contact form requires effort, most visitors leave. The path from interest to contact must be frictionless." },
      { title: "Bad local SEO", desc: "Studios in Marbella and Estepona are invisible to searches like 'architecture studio Marbella' or 'interior design Costa del Sol'." },
      { title: "Low trust for international clients", desc: "Multilingual presence, refined design, and professional copy reassure international buyers looking for a studio they can rely on." },
    ],
  },
  beforeAfter: {
    label: "The cold redesign offer",
    heading: "I do not start with a pitch. I start with proof.",
    body: "I redesign a key part of your website first, deploy it as a private Vercel preview, and send you the live link. If it feels right, we turn it into your real website.",
    cta: "Show me what my site could look like",
    before: "Before — generic, slow, hard to trust",
    after: "After — refined, editorial, conversion-clear",
  },
  services: {
    label: "What we do",
    heading: "Everything a studio needs to stand out online.",
    items: [
      {
        number: "01",
        title: "Website redesign for architecture studios",
        desc: "A refined digital presence that makes your portfolio easier to explore, your positioning clearer, and your studio more credible to high-value clients.",
        deliverables: ["Homepage redesign", "Project pages", "About page", "Enquiry flow", "Mobile experience", "Performance-focused build", "Multilingual setup"],
      },
      {
        number: "02",
        title: "Interior design studio websites",
        desc: "Elegant, image-led websites for studios that need to present mood, materials, style, and trust before the first meeting.",
        deliverables: ["Visual portfolio system", "Service pages", "Process storytelling", "Lead capture", "Instagram and portfolio integration"],
      },
      {
        number: "03",
        title: "Local SEO foundation",
        desc: "Technical and content structure to help studios appear for searches around Marbella, Estepona, Sotogrande, Málaga and the Costa del Sol.",
        deliverables: ["SEO metadata", "Local landing pages", "Structured data", "Internal linking", "Image alt structure", "Performance optimization"],
      },
      {
        number: "04",
        title: "Hosting & maintenance",
        desc: "Keep the website fast, secure, updated, and easy to manage without worrying about technical details.",
        deliverables: ["Vercel hosting setup", "Monthly updates", "Technical monitoring", "Small content edits", "Analytics checks"],
      },
      {
        number: "05",
        title: "Portfolio systems",
        desc: "A clean structure to publish projects consistently, including images, location, service type, materials, scope, and story.",
        deliverables: ["CMS-ready content model", "Project templates", "Filters by location and type", "Case study structure", "Image-first layout"],
      },
      {
        number: "06",
        title: "Brand refinement",
        desc: "Not a full branding agency replacement, but a sharp refinement of typography, color, layout, tone, and digital consistency.",
        deliverables: ["Visual direction", "Typography system", "Color system", "Website UI kit", "Basic brand guidelines"],
      },
    ],
  },
  method: {
    label: "The process",
    heading: "Six steps. No surprises.",
    steps: [
      { number: "01", title: "Audit", desc: "We review the current website, positioning, mobile experience, project presentation, and local search visibility." },
      { number: "02", title: "Direction", desc: "We define the visual direction, content structure, pages, SEO priorities, and conversion path." },
      { number: "03", title: "Design", desc: "We create a refined interface system with strong typography, image hierarchy, project storytelling, and responsive layouts." },
      { number: "04", title: "Build", desc: "We build a fast website with clean code, multilingual structure if needed, technical SEO, analytics, and deployment on Vercel." },
      { number: "05", title: "Launch", desc: "We connect domain, test performance, review mobile, polish metadata, and prepare the site for outreach or organic discovery." },
      { number: "06", title: "Maintain", desc: "Optional hosting, updates, portfolio publishing, SEO improvements, and monthly care." },
    ],
  },
  pricing: {
    label: "Pricing",
    heading: "Transparent pricing. No guesswork.",
    sub: "Starting prices. Final quote depends on number of pages, languages, CMS scope, and content readiness.",
    vatNote: "Prices shown excluding IVA when applicable.",
    paymentNote: "50% upfront, 50% before launch for projects above €790. Monthly plans billed monthly.",
    cta: "Request a quote",
    oneTime: [
      {
        name: "Audit Preview",
        price: "€190",
        desc: "Entry product for cold leads who want a professional assessment before committing.",
        includes: ["Website audit", "Homepage UX review", "Mobile review", "Visual direction notes", "SEO quick scan", "5 priority recommendations", "Optional redesign preview screenshot"],
        notIncluded: ["Full website build", "Copywriting", "Implementation"],
        cta: "Get an audit",
        featured: false,
      },
      {
        name: "Studio Refresh",
        price: "From €790",
        desc: "Affordable entry upgrade for studios with an outdated site that need a cleaner presence fast.",
        includes: ["1 to 3 pages", "Refined visual direction", "Responsive design", "Basic copy structure", "Contact CTA", "Performance optimization", "Vercel deployment", "Basic SEO setup", "1 language"],
        notIncluded: [] as string[],
        cta: "Request a quote",
        featured: false,
      },
      {
        name: "Signature Website",
        price: "From €1,900",
        desc: "Main offer for established studios that need a serious digital presence.",
        includes: ["5 to 7 pages", "Custom design system", "Multilingual optional", "Project portfolio structure", "Service pages", "About page", "Contact page", "Technical SEO", "Analytics setup", "Vercel deployment", "2 revision rounds"],
        notIncluded: [] as string[],
        cta: "Request a quote",
        featured: true,
      },
      {
        name: "Editorial Studio",
        price: "From €3,500",
        desc: "Premium offer for studios selling villas, renovations, interiors, and international projects.",
        includes: ["Full website strategy", "Custom art direction", "Multilingual EN/ES/FR", "Portfolio CMS", "Local SEO landing pages", "Advanced animations", "Case study templates", "Conversion strategy", "Analytics", "Launch support", "3 revision rounds"],
        notIncluded: [] as string[],
        cta: "Request a quote",
        featured: false,
      },
    ],
    recurring: [
      {
        name: "Hosting Care",
        price: "€49/month",
        desc: "Basic hosting and technical peace of mind.",
        includes: ["Vercel hosting management", "Technical checks", "Uptime monitoring", "Small monthly update", "Monthly backup check"],
      },
      {
        name: "Studio Care",
        price: "€149/month",
        desc: "Hosting plus regular content support.",
        includes: ["Everything in Hosting Care", "2 content edits per month", "Portfolio upload support", "Analytics review", "SEO checks"],
      },
      {
        name: "Growth Care",
        price: "€390/month",
        desc: "Full ongoing support with active SEO growth.",
        includes: ["Everything in Studio Care", "Local SEO improvements", "One new SEO page or article per month", "Search Console review", "Conversion improvements", "Monthly recommendation report"],
      },
    ],
    addons: [
      { name: "Extra language", price: "From €250" },
      { name: "Extra page", price: "From €180" },
      { name: "Project page upload", price: "From €90/project" },
      { name: "Google Business Profile", price: "From €190" },
      { name: "SEO city page", price: "From €250/page" },
      { name: "Copywriting refinement", price: "From €350" },
    ],
  },
  work: {
    label: "Concept studies",
    heading: "Direction and execution, demonstrated.",
    disclaimer: "These are concept studies created to show the level of direction and execution available. Real client work can be added later.",
    items: [
      { slug: "villa-architecture-studio", title: "Architecture Studio — Benahavís", category: "Architecture website", location: "Benahavís, Costa del Sol", challenge: "Studio with strong villa portfolio but an outdated, image-heavy website with no clear navigation or mobile layout.", what: "Homepage redesign, project pages, about section, and mobile-first rebuild with editorial layout and multilingual structure." },
      { slug: "interior-design-marbella", title: "Interior Design Studio — Marbella", category: "Interior design website", location: "Marbella, Costa del Sol", challenge: "Young studio producing high-quality interior work but invisible online. No SEO, no portfolio system, weak first impression.", what: "Brand refinement, website design, portfolio system, contact flow, and local SEO setup for Marbella and surrounding area." },
      { slug: "renovation-studio-estepona", title: "Villa Renovation Studio — Estepona", category: "Renovation website", location: "Estepona, Costa del Sol", challenge: "Renovation studio relying entirely on word of mouth. No digital presence, no Google visibility, no way for international clients to find them.", what: "Full website strategy, Vercel preview redesign sent by cold email, multilingual EN/ES setup, Google Business Profile optimization." },
      { slug: "project-page-system", title: "Portfolio Page System — Sotogrande", category: "Portfolio system", location: "Sotogrande, Costa del Sol", challenge: "Studio with 40+ projects and no consistent way to present them. All projects sat in a flat gallery with no context, materials, or story.", what: "CMS-ready project template, filterable by location and type, case study structure with before/after sections and material storytelling." },
    ],
  },
  audit: {
    label: "Free audit offer",
    heading: "Want to see what your studio website could become?",
    sub: "Send your current website. I will review the first impression, mobile experience, portfolio clarity, SEO basics, and enquiry flow — and send you a clear set of recommendations.",
    what: {
      heading: "What I review",
      items: ["First impression and visual credibility", "Mobile experience and responsiveness", "Portfolio clarity and project storytelling", "SEO basics and local search visibility", "Enquiry flow and conversion path", "Typography, spacing, and image quality", "Page speed basics", "Multilingual readiness"],
    },
    receive: {
      heading: "What you receive",
      items: ["Written audit PDF or document", "5 to 10 priority recommendations", "Visual direction notes", "Optional redesign preview screenshot", "Clear next step proposal"],
    },
    who: {
      heading: "Who this is for",
      items: ["Architecture studios on the Costa del Sol", "Interior design studios in Marbella or Estepona", "Studios preparing a relaunch", "Studios with outdated websites losing trust", "Studios targeting international clients"],
    },
    issues: {
      heading: "Common issues I find",
      items: ["Homepage with no clear hierarchy", "Gallery with no project context", "No mobile-optimized layout", "Zero local SEO structure", "Generic or outdated typography", "Missing contact path or buried form", "No multilingual version for international clients"],
    },
    form: {
      name: "Your name",
      studio: "Studio name",
      url: "Current website URL",
      email: "Email address",
      city: "City",
      type: "Type of studio",
      typeOptions: ["Architecture", "Interior design", "Real estate", "Other"],
      improve: "What do you most want to improve?",
      language: "Preferred language",
      consent: "I agree to be contacted about my audit request.",
      cta: "Request my audit",
      success: "Thank you. I will review your website and be in touch within 48 hours.",
    },
    faq: [
      { q: "Is the audit really free?", a: "The initial audit and written recommendations are included. If you want a full redesign preview or implementation, that moves into a paid project." },
      { q: "How long does it take?", a: "I aim to send the first review within 48 hours. More detailed audits with preview redesigns may take 3 to 5 working days." },
      { q: "Do I need to commit to anything?", a: "Not at all. The audit is a standalone deliverable. If you want to continue, we can discuss options." },
    ],
  },
  seo: {
    label: "Local SEO for studios",
    heading: "Your studio deserves to be found on the Costa del Sol.",
    sub: "Architecture and interior design are highly local businesses. International clients search with location intent. Local SEO makes the difference between being found and being invisible.",
    cities: [
      { name: "Marbella", desc: "One of the most competitive luxury markets in Spain. Studios here need strong local authority, Google Business optimization, and multilingual content to capture international villa buyers." },
      { name: "Estepona", desc: "A growing market for both renovation and new build architecture. Studios in Estepona benefit from targeted content around the local property boom." },
      { name: "Benahavís", desc: "Home to some of the most exclusive villa developments in Europe. Architecture studios here need websites that match the premium standard of the market." },
      { name: "Sotogrande", desc: "High-end residential and equestrian market with strong international buyer base. Local search visibility for English and French speakers is critical." },
      { name: "Málaga", desc: "The regional hub with growing demand for interior design and architecture services. Proximity to the airport makes it a key entry point for international projects." },
      { name: "Mijas", desc: "Popular among Nordic and British buyers. Studios serving Mijas should optimize for multilingual search and Google Maps visibility." },
      { name: "Fuengirola", desc: "Dense residential market with active property renovation sector. Cost-effective SEO opportunity for smaller studios." },
      { name: "Casares", desc: "Boutique rural market with prestige villa projects. Niche positioning and local SEO can create strong organic authority." },
    ],
    sections: [
      { title: "Why local SEO matters for architecture studios", body: "Searches like 'architecture studio Marbella' or 'interior design website Estepona' have high buying intent. These searches come from property developers, villa owners, and international buyers who are ready to hire. Without local SEO structure, your studio is invisible to exactly the clients you want." },
      { title: "Project pages as SEO assets", body: "Each completed project is a piece of indexable content. A well-structured project page with location, scope, materials, and photography can rank for long-tail searches and drive discovery from property buyers and investors." },
      { title: "Multilingual SEO", body: "British, German, French, and Scandinavian buyers are active in the Costa del Sol market. A multilingual website with proper hreflang structure gives your studio visibility across language groups that your competitors probably miss." },
      { title: "Google Business Profile", body: "A fully optimized Google Business Profile positions your studio on Google Maps and in local search results. This is often the first touchpoint for local discovery and requires consistent name, address, and category data." },
      { title: "Technical SEO", body: "Site speed, Core Web Vitals, clean URL structure, structured data, and internal linking all affect how Google sees and ranks your website. We handle the technical foundation so the content can do its work." },
    ],
  },
  contact: {
    label: "Get in touch",
    heading: "Start with a conversation.",
    sub: "Tell us about your studio and what you want to improve. We will get back to you within 24 hours.",
    locations: "Serving studios across Marbella, Estepona, Benahavís, Sotogrande, Málaga, Mijas, Fuengirola, Casares, San Pedro, and Nueva Andalucía.",
    response: "Typical response within 24 hours. For urgent projects, mention it in your message.",
    form: {
      name: "Your name",
      email: "Email address",
      studio: "Studio name",
      city: "City",
      type: "Project type",
      typeOptions: ["Website redesign", "New website", "Local SEO", "Hosting and maintenance", "Portfolio system", "Brand refinement", "Not sure yet"],
      budget: "Budget range",
      budgetOptions: ["Under €750", "€750 to €1,500", "€1,500 to €3,500", "€3,500+", "Monthly care only"],
      message: "Tell us about your studio and goals",
      cta: "Send message",
      success: "Message received. We will be in touch within 24 hours.",
    },
  },
  faq: [
    { q: "Do you work with studios outside the Costa del Sol?", a: "Our focus is the Costa del Sol, but we are happy to take enquiries from studios elsewhere in Spain or from international studios serving Spanish clients." },
    { q: "How long does a website redesign take?", a: "A Studio Refresh takes 1 to 2 weeks. A Signature Website takes 3 to 5 weeks. An Editorial Studio project takes 6 to 10 weeks depending on scope and content readiness." },
    { q: "Do I need to provide the copy?", a: "We can work with your existing copy or refine it. Copywriting from scratch is available as an add-on." },
    { q: "What if I do not have professional photography?", a: "We design with the photography you have and advise on what kind of imagery would strengthen the studio. Professional photography is not required to launch." },
    { q: "Is the Vercel preview redesign free?", a: "The cold outreach redesign previews I create as part of my process are internal. If you received a preview link and want to discuss turning it into your real website, the conversation starts there." },
    { q: "Can you manage the website ongoing?", a: "Yes. Hosting Care, Studio Care, and Growth Care plans provide ongoing support at monthly rates starting from €49." },
    { q: "Do you offer multilingual websites?", a: "Yes. We build websites in English, Spanish, and French. Additional languages are available as add-ons." },
  ],
  footer: {
    tagline: "Digital presence for architecture and interior studios on the Costa del Sol.",
    locations: "Marbella · Estepona · Benahavís · Sotogrande · Málaga · Mijas · Fuengirola · Casares · San Pedro · Nueva Andalucía",
    email: "hello@formacosta.com",
    whatsapp: "+34 600 000 000",
    legal: { privacy: "Privacy Policy", terms: "Terms", cookies: "Cookies" },
    copy: "© 2025 FORMA COSTA. All rights reserved.",
    nav: {
      sitemap: "Sitemap",
      services: "Services",
      pricing: "Pricing",
      method: "Method",
      work: "Work",
      audit: "Free Audit",
      seo: "SEO",
      contact: "Contact",
    },
  },
} as const;

export default en;
