const fr = {
  nav: {
    services: "Services",
    pricing: "Tarifs",
    method: "Méthode",
    work: "Réalisations",
    audit: "Audit",
    seo: "SEO",
    contact: "Contact",
    cta: "Demander un audit",
  },
  hero: {
    label: "Studio digital pour l'architecture et le design d'intérieur",
    headline: "Votre travail est déjà premium. Votre site devrait l'être aussi.",
    sub: "FORMA COSTA crée des sites web raffinés, des systèmes de portfolio et des fondations SEO local pour les studios d'architecture et de design d'intérieur sur la Costa del Sol.",
    ctaPrimary: "Demander un audit de site",
    ctaSecondary: "Voir la méthode",
    proof: "Conçu pour les studios à Marbella, Estepona, Sotogrande, Benahavís et Málaga.",
  },
  problem: {
    heading: "La plupart des studios perdent la confiance avant le premier appel.",
    body: "L'architecture et le design d'intérieur sont des métiers visuels. Quand un site semble obsolète, lent, générique ou difficile à naviguer, la qualité du studio est jugée avant même que le visiteur voie correctement le travail.",
    cards: [
      { title: "Première impression dépassée", desc: "Les visiteurs jugent le studio en moins de trois secondes. Un décalage visuel entre le travail réel et le site érode la confiance instantanément." },
      { title: "Narration de projets faible", desc: "Les projets méritent plus qu'une grille de galerie. Chaque réalisation devrait communiquer la portée, les matériaux, le défi et le résultat." },
      { title: "Mauvaise expérience mobile", desc: "La plupart des demandes commencent sur un téléphone. Un site de studio qui s'effondre sur mobile envoie immédiatement le mauvais signal." },
      { title: "Pas de chemin de contact clair", desc: "Si trouver le formulaire de contact demande un effort, la plupart des visiteurs partent. Le chemin de l'intérêt au contact doit être sans friction." },
      { title: "Mauvais SEO local", desc: "Les studios à Marbella et Estepona sont invisibles pour des recherches comme 'studio d'architecture Marbella' ou 'design d'intérieur Costa del Sol'." },
      { title: "Peu de confiance pour les clients internationaux", desc: "Une présence multilingue, un design raffiné et des textes professionnels rassurent les acheteurs internationaux qui cherchent un studio fiable." },
    ],
  },
  beforeAfter: {
    label: "L'offre de refonte à froid",
    heading: "Je ne commence pas par un pitch. Je commence par une preuve.",
    body: "Je refais une partie clé de votre site en premier, je la déploie comme aperçu privé sur Vercel et je vous envoie le lien en direct. Si cela vous convient, nous en faisons votre vrai site.",
    cta: "Montrez-moi à quoi pourrait ressembler mon site",
    before: "Avant — générique, lent, peu crédible",
    after: "Après — raffiné, éditorial, clair pour convertir",
  },
  services: {
    label: "Ce que nous faisons",
    heading: "Tout ce qu'un studio a besoin pour se démarquer en ligne.",
    items: [
      {
        number: "01",
        title: "Refonte de site pour studios d'architecture",
        desc: "Une présence digitale raffinée qui rend votre portfolio plus facile à explorer, votre positionnement plus clair et votre studio plus crédible auprès de clients à haute valeur.",
        deliverables: ["Refonte de la page d'accueil", "Pages de projets", "Page à propos", "Parcours de demande", "Expérience mobile", "Construction axée sur la performance", "Configuration multilingue"],
      },
      {
        number: "02",
        title: "Sites pour studios de design d'intérieur",
        desc: "Des sites web élégants et visuels pour les studios qui ont besoin de présenter l'ambiance, les matériaux, le style et la confiance avant la première réunion.",
        deliverables: ["Système de portfolio visuel", "Pages de services", "Narration du processus", "Captation de leads", "Intégration Instagram et portfolio"],
      },
      {
        number: "03",
        title: "Fondation SEO local",
        desc: "Structure technique et de contenu pour aider les studios à apparaître dans les recherches autour de Marbella, Estepona, Sotogrande, Málaga et la Costa del Sol.",
        deliverables: ["Métadonnées SEO", "Pages d'atterrissage locales", "Données structurées", "Maillage interne", "Structure alt des images", "Optimisation des performances"],
      },
      {
        number: "04",
        title: "Hébergement et maintenance",
        desc: "Gardez le site rapide, sécurisé, mis à jour et facile à gérer sans vous soucier des détails techniques.",
        deliverables: ["Configuration d'hébergement Vercel", "Mises à jour mensuelles", "Surveillance technique", "Petites modifications de contenu", "Vérifications analytiques"],
      },
      {
        number: "05",
        title: "Systèmes de portfolio",
        desc: "Une structure propre pour publier des projets de manière cohérente, incluant les images, la localisation, le type de service, les matériaux, la portée et l'histoire.",
        deliverables: ["Modèle de contenu compatible CMS", "Modèles de projets", "Filtres par localisation et type", "Structure d'étude de cas", "Mise en page centrée sur l'image"],
      },
      {
        number: "06",
        title: "Raffinement de marque",
        desc: "Pas un remplacement d'agence de branding complète, mais un affinement précis de la typographie, la couleur, la mise en page, le ton et la cohérence digitale.",
        deliverables: ["Direction visuelle", "Système typographique", "Système de couleurs", "Kit UI pour le site", "Lignes directrices de marque de base"],
      },
    ],
  },
  method: {
    label: "Le processus",
    heading: "Six étapes. Pas de surprises.",
    steps: [
      { number: "01", title: "Audit", desc: "Nous examinons le site actuel, le positionnement, l'expérience mobile, la présentation des projets et la visibilité dans les recherches locales." },
      { number: "02", title: "Direction", desc: "Nous définissons la direction visuelle, la structure du contenu, les pages, les priorités SEO et le chemin de conversion." },
      { number: "03", title: "Design", desc: "Nous créons un système d'interface raffiné avec une typographie solide, une hiérarchie d'images, une narration de projets et des mises en page responsives." },
      { number: "04", title: "Construction", desc: "Nous construisons un site rapide avec du code propre, une structure multilingue si nécessaire, le SEO technique, l'analytique et le déploiement sur Vercel." },
      { number: "05", title: "Lancement", desc: "Nous connectons le domaine, testons les performances, révisons le mobile, peaufinons les métadonnées et préparons le site pour la diffusion ou la découverte organique." },
      { number: "06", title: "Maintenance", desc: "Hébergement optionnel, mises à jour, publication de portfolio, améliorations SEO et suivi mensuel." },
    ],
  },
  pricing: {
    label: "Tarifs",
    heading: "Tarifs transparents. Pas d'approximations.",
    sub: "Prix de départ. Le devis final dépend du nombre de pages, des langues, de la portée du CMS et de la disponibilité du contenu.",
    vatNote: "Prix indiqués hors TVA le cas échéant.",
    paymentNote: "50% à l'avance, 50% avant le lancement pour les projets supérieurs à €790. Les plans mensuels sont facturés mensuellement.",
    cta: "Demander un devis",
    oneTime: [
      {
        name: "Aperçu d'audit",
        price: "€190",
        desc: "Produit d'entrée pour ceux qui souhaitent une évaluation professionnelle avant de s'engager.",
        includes: ["Audit de site", "Révision UX de la page d'accueil", "Révision mobile", "Notes de direction visuelle", "Analyse rapide SEO", "5 recommandations prioritaires", "Capture d'écran de refonte optionnelle"],
        notIncluded: ["Construction complète du site", "Rédaction de contenu", "Implémentation"],
        cta: "Obtenir un audit",
        featured: false,
      },
      {
        name: "Actualisation studio",
        price: "À partir de €790",
        desc: "Amélioration d'entrée abordable pour les studios avec un site obsolète qui ont besoin d'une présence plus propre rapidement.",
        includes: ["1 à 3 pages", "Direction visuelle raffinée", "Design responsive", "Structure de texte de base", "CTA de contact", "Optimisation des performances", "Déploiement Vercel", "Configuration SEO de base", "1 langue"],
        notIncluded: [] as string[],
        cta: "Demander un devis",
        featured: false,
      },
      {
        name: "Site Signature",
        price: "À partir de €1.900",
        desc: "Offre principale pour les studios établis qui ont besoin d'une présence digitale sérieuse.",
        includes: ["5 à 7 pages", "Système de design personnalisé", "Multilingue optionnel", "Structure de portfolio de projets", "Pages de services", "Page à propos", "Page de contact", "SEO technique", "Configuration analytique", "Déploiement Vercel", "2 tours de révision"],
        notIncluded: [] as string[],
        cta: "Demander un devis",
        featured: true,
      },
      {
        name: "Studio Éditorial",
        price: "À partir de €3.500",
        desc: "Offre premium pour les studios vendant des villas, rénovations, intérieurs et projets internationaux.",
        includes: ["Stratégie web complète", "Direction artistique personnalisée", "Multilingue EN/ES/FR", "CMS de portfolio", "Pages d'atterrissage SEO local", "Animations avancées", "Modèles d'études de cas", "Stratégie de conversion", "Analytique", "Support au lancement", "3 tours de révision"],
        notIncluded: [] as string[],
        cta: "Demander un devis",
        featured: false,
      },
    ],
    recurring: [
      {
        name: "Soin hébergement",
        price: "€49/mois",
        desc: "Hébergement de base et tranquillité technique.",
        includes: ["Gestion d'hébergement Vercel", "Vérifications techniques", "Surveillance de disponibilité", "Petite mise à jour mensuelle", "Vérification mensuelle des sauvegardes"],
      },
      {
        name: "Soin studio",
        price: "€149/mois",
        desc: "Hébergement plus support de contenu régulier.",
        includes: ["Tout dans Soin hébergement", "2 modifications de contenu par mois", "Support pour télécharger le portfolio", "Révision analytique", "Vérifications SEO"],
      },
      {
        name: "Soin croissance",
        price: "€390/mois",
        desc: "Support continu complet avec croissance SEO active.",
        includes: ["Tout dans Soin studio", "Améliorations SEO local", "Une nouvelle page ou article SEO par mois", "Révision Search Console", "Améliorations de conversion", "Rapport de recommandations mensuel"],
      },
    ],
    addons: [
      { name: "Langue supplémentaire", price: "À partir de €250" },
      { name: "Page supplémentaire", price: "À partir de €180" },
      { name: "Téléchargement de page de projet", price: "À partir de €90/projet" },
      { name: "Google Business Profile", price: "À partir de €190" },
      { name: "Page SEO de ville", price: "À partir de €250/page" },
      { name: "Raffinement de la rédaction", price: "À partir de €350" },
    ],
  },
  work: {
    label: "Études de concept",
    heading: "Direction et exécution, démontrées.",
    disclaimer: "Ce sont des études de concept créées pour montrer le niveau de direction et d'exécution disponible. Le vrai travail client peut être ajouté ultérieurement.",
    items: [
      { slug: "villa-architecture-studio", title: "Studio d'Architecture — Benahavís", category: "Site d'architecture", location: "Benahavís, Costa del Sol", challenge: "Studio avec un solide portfolio de villas mais un site obsolète et surchargé d'images, sans navigation claire ni mise en page mobile.", what: "Refonte de la page d'accueil, pages de projets, section à propos et reconstruction mobile-first avec mise en page éditoriale et structure multilingue." },
      { slug: "interior-design-marbella", title: "Studio de Design d'Intérieur — Marbella", category: "Site de design d'intérieur", location: "Marbella, Costa del Sol", challenge: "Jeune studio produisant un travail d'intérieur de haute qualité mais invisible en ligne. Pas de SEO, pas de système de portfolio, première impression faible.", what: "Raffinement de marque, design de site, système de portfolio, parcours de contact et configuration SEO local pour Marbella et les environs." },
      { slug: "renovation-studio-estepona", title: "Studio de Rénovation de Villas — Estepona", category: "Site de rénovation", location: "Estepona, Costa del Sol", challenge: "Studio de rénovation reposant entièrement sur le bouche-à-oreille. Pas de présence digitale, pas de visibilité sur Google, aucun moyen pour les clients internationaux de les trouver.", what: "Stratégie web complète, refonte aperçu Vercel envoyée par email à froid, configuration multilingue EN/ES, optimisation du Google Business Profile." },
      { slug: "project-page-system", title: "Système de Pages de Portfolio — Sotogrande", category: "Système de portfolio", location: "Sotogrande, Costa del Sol", challenge: "Studio avec plus de 40 projets et aucun moyen cohérent de les présenter. Tous les projets étaient dans une galerie plate sans contexte, matériaux ni histoire.", what: "Modèle de projet compatible CMS, filtrable par localisation et type, structure d'étude de cas avec sections avant/après et narration de matériaux." },
    ],
  },
  audit: {
    label: "Offre d'audit gratuit",
    heading: "Vous voulez voir ce que votre site de studio pourrait devenir?",
    sub: "Envoyez votre site actuel. Je réviserai la première impression, l'expérience mobile, la clarté du portfolio, les bases SEO et le parcours de contact — et je vous enverrai un ensemble clair de recommandations.",
    what: {
      heading: "Ce que je révise",
      items: ["Première impression et crédibilité visuelle", "Expérience mobile et réactivité", "Clarté du portfolio et narration de projets", "Bases SEO et visibilité dans la recherche locale", "Parcours de demande et chemin de conversion", "Typographie, espacement et qualité d'image", "Bases de la vitesse de page", "Préparation multilingue"],
    },
    receive: {
      heading: "Ce que vous recevez",
      items: ["Audit écrit en PDF ou document", "5 à 10 recommandations prioritaires", "Notes de direction visuelle", "Capture d'écran de refonte optionnelle", "Proposition d'étape suivante claire"],
    },
    who: {
      heading: "Pour qui c'est",
      items: ["Studios d'architecture sur la Costa del Sol", "Studios de design d'intérieur à Marbella ou Estepona", "Studios préparant un relancement", "Studios avec des sites obsolètes qui perdent la confiance", "Studios ciblant des clients internationaux"],
    },
    issues: {
      heading: "Problèmes courants que je trouve",
      items: ["Page d'accueil sans hiérarchie claire", "Galerie sans contexte de projet", "Pas de mise en page optimisée pour mobile", "Zéro structure SEO local", "Typographie générique ou obsolète", "Chemin de contact manquant ou formulaire enfoui", "Pas de version multilingue pour les clients internationaux"],
    },
    form: {
      name: "Votre nom",
      studio: "Nom du studio",
      url: "URL du site actuel",
      email: "Adresse email",
      city: "Ville",
      type: "Type de studio",
      typeOptions: ["Architecture", "Design d'intérieur", "Immobilier", "Autre"],
      improve: "Qu'est-ce que vous souhaitez le plus améliorer?",
      language: "Langue préférée",
      consent: "J'accepte d'être contacté(e) au sujet de ma demande d'audit.",
      cta: "Demander mon audit",
      success: "Merci. Je réviserai votre site et vous contacterai dans les 48 heures.",
    },
    faq: [
      { q: "L'audit est-il vraiment gratuit?", a: "L'audit initial et les recommandations écrites sont inclus. Si vous souhaitez un aperçu complet de la refonte ou une implémentation, cela devient un projet payant." },
      { q: "Combien de temps cela prend-il?", a: "Je vise à envoyer la première révision dans les 48 heures. Les audits plus détaillés avec des aperçus de refonte peuvent prendre 3 à 5 jours ouvrables." },
      { q: "Dois-je m'engager à quelque chose?", a: "Pas du tout. L'audit est un livrable autonome. Si vous souhaitez continuer, nous pouvons discuter des options." },
    ],
  },
  seo: {
    label: "SEO local pour studios",
    heading: "Votre studio mérite d'être trouvé sur la Costa del Sol.",
    sub: "L'architecture et le design d'intérieur sont des métiers très locaux. Les clients internationaux cherchent avec une intention de localisation. Le SEO local fait la différence entre être trouvé et être invisible.",
    cities: [
      { name: "Marbella", desc: "L'un des marchés de luxe les plus compétitifs d'Espagne. Les studios ici ont besoin d'une forte autorité locale, d'une optimisation Google Business et d'un contenu multilingue pour capter les acheteurs internationaux de villas." },
      { name: "Estepona", desc: "Un marché en croissance pour la rénovation et la nouvelle construction architecturale. Les studios à Estepona bénéficient d'un contenu ciblé autour du boom immobilier local." },
      { name: "Benahavís", desc: "Foyer de certains des développements de villas les plus exclusifs d'Europe. Les studios d'architecture ici ont besoin de sites qui correspondent au standard premium du marché." },
      { name: "Sotogrande", desc: "Marché résidentiel et équestre haut de gamme avec une forte base d'acheteurs internationaux. La visibilité dans les recherches locales pour les anglophones et francophones est essentielle." },
      { name: "Málaga", desc: "Le hub régional avec une demande croissante de services de design d'intérieur et d'architecture. La proximité de l'aéroport en fait un point d'entrée clé pour les projets internationaux." },
      { name: "Mijas", desc: "Populaire parmi les acheteurs nordiques et britanniques. Les studios servant Mijas devraient optimiser pour la recherche multilingue et la visibilité sur Google Maps." },
      { name: "Fuengirola", desc: "Marché résidentiel dense avec un secteur actif de rénovation immobilière. Opportunité SEO rentable pour les petits studios." },
      { name: "Casares", desc: "Marché rural boutique avec des projets de villas de prestige. Le positionnement de niche et le SEO local peuvent créer une solide autorité organique." },
    ],
    sections: [
      { title: "Pourquoi le SEO local est important pour les studios d'architecture", body: "Des recherches comme 'studio d'architecture Marbella' ou 'site de design d'intérieur Estepona' ont une forte intention d'achat. Ces recherches viennent de promoteurs immobiliers, propriétaires de villas et acheteurs internationaux prêts à engager. Sans structure SEO local, votre studio est invisible exactement pour les clients que vous souhaitez." },
      { title: "Les pages de projets comme actifs SEO", body: "Chaque projet terminé est un contenu indexable. Une page de projet bien structurée avec localisation, portée, matériaux et photographie peut se positionner pour des recherches longue traîne et stimuler la découverte par des acheteurs et investisseurs immobiliers." },
      { title: "SEO multilingue", body: "Les acheteurs britanniques, allemands, français et scandinaves sont actifs sur le marché de la Costa del Sol. Un site multilingue avec une structure hreflang correcte donne à votre studio une visibilité dans des groupes linguistiques que vos concurrents ignorent probablement." },
      { title: "Google Business Profile", body: "Un Google Business Profile entièrement optimisé positionne votre studio sur Google Maps et dans les résultats de recherche locale. C'est souvent le premier point de contact pour la découverte locale et nécessite des données cohérentes de nom, d'adresse et de catégorie." },
      { title: "SEO technique", body: "La vitesse du site, les Core Web Vitals, une structure d'URL propre, les données structurées et le maillage interne affectent tous la façon dont Google voit et classe votre site. Nous nous occupons de la fondation technique pour que le contenu puisse faire son travail." },
    ],
  },
  contact: {
    label: "Prendre contact",
    heading: "Commencez par une conversation.",
    sub: "Parlez-nous de votre studio et de ce que vous souhaitez améliorer. Nous vous répondrons dans les 24 heures.",
    locations: "Au service des studios à Marbella, Estepona, Benahavís, Sotogrande, Málaga, Mijas, Fuengirola, Casares, San Pedro et Nueva Andalucía.",
    response: "Réponse typique dans les 24 heures. Pour les projets urgents, mentionnez-le dans votre message.",
    form: {
      name: "Votre nom",
      email: "Adresse email",
      studio: "Nom du studio",
      city: "Ville",
      type: "Type de projet",
      typeOptions: ["Refonte de site", "Nouveau site", "SEO local", "Hébergement et maintenance", "Système de portfolio", "Raffinement de marque", "Pas encore décidé"],
      budget: "Fourchette de budget",
      budgetOptions: ["Moins de €750", "€750 à €1.500", "€1.500 à €3.500", "€3.500+", "Soin mensuel uniquement"],
      message: "Parlez-nous de votre studio et de vos objectifs",
      cta: "Envoyer le message",
      success: "Message reçu. Nous vous contacterons dans les 24 heures.",
    },
  },
  faq: [
    { q: "Travaillez-vous avec des studios en dehors de la Costa del Sol?", a: "Notre focus est la Costa del Sol, mais nous sommes heureux de recevoir des demandes de studios ailleurs en Espagne ou de studios internationaux servant des clients espagnols." },
    { q: "Combien de temps prend une refonte de site?", a: "Une Actualisation Studio prend 1 à 2 semaines. Un Site Signature prend 3 à 5 semaines. Un projet de Studio Éditorial prend 6 à 10 semaines selon la portée et la disponibilité du contenu." },
    { q: "Dois-je fournir les textes?", a: "Nous pouvons travailler avec vos textes existants ou les raffiner. La rédaction depuis zéro est disponible en option complémentaire." },
    { q: "Et si je n'ai pas de photographie professionnelle?", a: "Nous concevons avec les photos que vous avez et conseillons sur le type d'images qui renforcerait le studio. La photographie professionnelle n'est pas nécessaire pour le lancement." },
    { q: "L'aperçu de refonte Vercel est-il gratuit?", a: "Les aperçus de refonte que je crée dans le cadre de mon processus de prospection à froid sont internes. Si vous avez reçu un lien d'aperçu et souhaitez discuter de le transformer en votre vrai site, la conversation commence là." },
    { q: "Pouvez-vous gérer le site en continu?", a: "Oui. Les plans Soin Hébergement, Soin Studio et Soin Croissance offrent un support continu à des tarifs mensuels à partir de €49." },
    { q: "Proposez-vous des sites multilingues?", a: "Oui. Nous construisons des sites en anglais, espagnol et français. Des langues supplémentaires sont disponibles en option." },
  ],
  footer: {
    tagline: "Présence digitale pour les studios d'architecture et d'intérieur sur la Costa del Sol.",
    locations: "Marbella · Estepona · Benahavís · Sotogrande · Málaga · Mijas · Fuengirola · Casares · San Pedro · Nueva Andalucía",
    email: "hello@formacosta.com",
    whatsapp: "+34 600 000 000",
    legal: { privacy: "Politique de confidentialité", terms: "Conditions", cookies: "Cookies" },
    copy: "© 2025 FORMA COSTA. Tous droits réservés.",
    nav: {
      sitemap: "Plan du site",
      services: "Services",
      pricing: "Tarifs",
      method: "Méthode",
      work: "Réalisations",
      audit: "Audit gratuit",
      seo: "SEO",
      contact: "Contact",
    },
  },
} as const;

export default fr;
