const fr = {
  nav: {
    services: "Refontes",
    pricing: "Tarifs",
    method: "Méthode",
    work: "Réalisations",
    audit: "Audit",
    seo: "SEO",
    contact: "Contact",
    cta: "Commencer le site",
  },
  hero: {
    label: "Refontes de sites d'architecture",
    headline: "Votre studio paraît déjà premium. Votre site devrait aussi.",
    sub: "Refontes raffinées pour studios d'architecture et de design intérieur à Marbella, Estepona, Sotogrande, Benahavís et Málaga.",
    ctaPrimary: "Voir les previews",
    ctaSecondary: "Demander une revue",
    proof: "Conçu pour les studios à Marbella, Estepona, Sotogrande, Benahavís et Málaga.",
  },
  problem: {
    heading: "La plupart des studios perdent la confiance avant le premier appel.",
    body: "L'architecture et le design d'intérieur sont des métiers visuels. Quand un site semble obsolète, lent, générique ou difficile à naviguer, la qualité du studio est jugée avant même que le visiteur voie correctement le travail.",
    cards: [
      { title: "Première impression dépassée", desc: "Les visiteurs jugent le studio en moins de trois secondes. Un décalage visuel entre le travail réel et le site érode la confiance instantanément." },
      { title: "Narration de projets faible", desc: "Les projets méritent plus qu'une grille de galerie. Chaque réalisation devrait communiquer la portée, les matériaux, le défi et le résultat." },
      { title: "Mauvaise expérience mobile", desc: "La plupart des demandes commencent sur un téléphone. Un site de studio qui s'effondre sur mobile envoie immédiatement le mauvais signal." },
      { title: "Pas de chemin de contact clair", desc: "Si trouver le formulaire de contact demande un effort, la plupart des visiteurs partent. Le chemin de l'intérêt au contact doit être sans friction." },
      { title: "Mauvais SEO local", desc: "Les studios à Marbella et Estepona sont invisibles pour des recherches comme 'studio d'architecture Marbella' ou 'design d'intérieur Costa del Sol'." },
      { title: "Peu de confiance pour les clients internationaux", desc: "Une présence multilingue, un design raffiné et des textes professionnels rassurent les acheteurs internationaux qui cherchent un studio fiable." },
    ],
  },
  beforeAfter: {
    label: "L'offre de refonte à froid",
    heading: "Je ne commence pas par un pitch. Je commence par une preuve.",
    body: "Je refais une partie clé de votre site en premier, je la déploie comme aperçu privé sur Vercel et je vous envoie le lien en direct. Si cela vous convient, nous en faisons votre vrai site.",
    cta: "Montrez-moi à quoi pourrait ressembler mon site",
    before: "Avant - générique, lent, peu crédible",
    after: "Après - raffiné, éditorial, clair pour convertir",
  },
  services: {
    label: "Ce que nous faisons",
    heading: "Tout ce qu'un studio a besoin pour se démarquer en ligne.",
    items: [
      {
        number: "01",
        title: "Refonte de site pour studios d'architecture",
        desc: "Une présence digitale raffinée qui rend votre portfolio plus facile à explorer, votre positionnement plus clair et votre studio plus crédible auprès de clients à haute valeur.",
        deliverables: ["Refonte de la page d'accueil", "Pages de projets", "Page à propos", "Parcours de demande", "Expérience mobile", "Construction axée sur la performance", "Configuration multilingue"],
      },
      {
        number: "02",
        title: "Sites pour studios de design d'intérieur",
        desc: "Des sites web élégants et visuels pour les studios qui ont besoin de présenter l'ambiance, les matériaux, le style et la confiance avant la première réunion.",
        deliverables: ["Système de portfolio visuel", "Pages de services", "Narration du processus", "Captation de leads", "Intégration Instagram et portfolio"],
      },
      {
        number: "03",
        title: "Fondation SEO local",
        desc: "Structure technique et de contenu pour aider les studios à apparaître dans les recherches autour de Marbella, Estepona, Sotogrande, Málaga et la Costa del Sol.",
        deliverables: ["Métadonnées SEO", "Pages d'atterrissage locales", "Données structurées", "Maillage interne", "Structure alt des images", "Optimisation des performances"],
      },
      {
        number: "04",
        title: "Hébergement et maintenance",
        desc: "Gardez le site rapide, sécurisé, mis à jour et facile à gérer sans vous soucier des détails techniques.",
        deliverables: ["Configuration d'hébergement Vercel", "Mises à jour mensuelles", "Surveillance technique", "Petites modifications de contenu", "Vérifications analytiques"],
      },
      {
        number: "05",
        title: "Systèmes de portfolio",
        desc: "Une structure propre pour publier des projets de manière cohérente, incluant les images, la localisation, le type de service, les matériaux, la portée et l'histoire.",
        deliverables: ["Modèle de contenu compatible CMS", "Modèles de projets", "Filtres par localisation et type", "Structure d'étude de cas", "Mise en page centrée sur l'image"],
      },
      {
        number: "06",
        title: "Raffinement de marque",
        desc: "Pas un remplacement d'agence de branding complète, mais un affinement précis de la typographie, la couleur, la mise en page, le ton et la cohérence digitale.",
        deliverables: ["Direction visuelle", "Système typographique", "Système de couleurs", "Kit UI pour le site", "Lignes directrices de marque de base"],
      },
    ],
  },
  method: {
    label: "Le processus",
    heading: "La preview vient d'abord.",
    steps: [
      { number: "01", title: "Je refais une partie de votre site", desc: "Une direction ciblée pour la page d'accueil ou une page projet, créée avant la conversation commerciale." },
      { number: "02", title: "Vous examinez la preview", desc: "Vous ouvrez un lien privé Vercel et voyez la direction sur desktop et mobile." },
      { number: "03", title: "Je finalise le système", desc: "La direction validée devient un site responsive complet avec portfolio et base multilingue." },
      { number: "04", title: "Nous lançons", desc: "Le site est déployé, testé, connecté et prêt à être utilisé avec confiance." },
      { number: "05", title: "Lancement", desc: "Nous connectons le domaine, testons les performances, révisons le mobile, peaufinons les métadonnées et préparons le site pour la diffusion ou la découverte organique." },
      { number: "06", title: "Maintenance", desc: "Hébergement optionnel, mises à jour, publication de portfolio, améliorations SEO et suivi mensuel." },
    ],
  },
  pricing: {
    label: "Tarifs",
    heading: "Tarifs transparents. Pas d'approximations.",
    sub: "Prix de départ. Le devis final dépend du nombre de pages, des langues, de la portée du CMS et de la disponibilité du contenu.",
    vatNote: "Prix indiqués hors TVA le cas échéant.",
    paymentNote: "50% à l'avance, 50% avant le lancement pour les projets supérieurs à €790. Les plans mensuels sont facturés mensuellement.",
    cta: "Demander un devis",
    oneTime: [
      {
        name: "Aperçu d'audit",
        price: "€190",
        desc: "Produit d'entrée pour ceux qui souhaitent une évaluation professionnelle avant de s'engager.",
        includes: ["Audit de site", "Révision UX de la page d'accueil", "Révision mobile", "Notes de direction visuelle", "Analyse rapide SEO", "5 recommandations prioritaires", "Capture d'écran de refonte optionnelle"],
        notIncluded: ["Construction complète du site", "Rédaction de contenu", "Implémentation"],
        cta: "Obtenir un audit",
        featured: false,
      },
      {
        name: "Actualisation studio",
        price: "À partir de €790",
        desc: "Amélioration d'entrée abordable pour les studios avec un site obsolète qui ont besoin d'une présence plus propre rapidement.",
        includes: ["1 à 3 pages", "Direction visuelle raffinée", "Design responsive", "Structure de texte de base", "CTA de contact", "Optimisation des performances", "Déploiement Vercel", "Configuration SEO de base", "1 langue"],
        notIncluded: [] as string[],
        cta: "Demander un devis",
        featured: false,
      },
      {
        name: "Site Signature",
        price: "À partir de €1.900",
        desc: "Offre principale pour les studios établis qui ont besoin d'une présence digitale sérieuse.",
        includes: ["5 à 7 pages", "Système de design personnalisé", "Multilingue optionnel", "Structure de portfolio de projets", "Pages de services", "Page à propos", "Page de contact", "SEO technique", "Configuration analytique", "Déploiement Vercel", "2 tours de révision"],
        notIncluded: [] as string[],
        cta: "Demander un devis",
        featured: true,
      },
      {
        name: "Studio Éditorial",
        price: "À partir de €3.500",
        desc: "Offre premium pour les studios vendant des villas, rénovations, intérieurs et projets internationaux.",
        includes: ["Stratégie web complète", "Direction artistique personnalisée", "Multilingue EN/ES/FR", "CMS de portfolio", "Pages d'atterrissage SEO local", "Animations avancées", "Modèles d'études de cas", "Stratégie de conversion", "Analytique", "Support au lancement", "3 tours de révision"],
        notIncluded: [] as string[],
        cta: "Demander un devis",
        featured: false,
      },
    ],
    recurring: [
      {
        name: "Soin hébergement",
        price: "€49/mois",
        desc: "Hébergement de base et tranquillité technique.",
        includes: ["Gestion d'hébergement Vercel", "Vérifications techniques", "Surveillance de disponibilité", "Petite mise à jour mensuelle", "Vérification mensuelle des sauvegardes"],
      },
      {
        name: "Soin studio",
        price: "€149/mois",
        desc: "Hébergement plus support de contenu régulier.",
        includes: ["Tout dans Soin hébergement", "2 modifications de contenu par mois", "Support pour télécharger le portfolio", "Révision analytique", "Vérifications SEO"],
      },
      {
        name: "Soin croissance",
        price: "€390/mois",
        desc: "Support continu complet avec croissance SEO active.",
        includes: ["Tout dans Soin studio", "Améliorations SEO local", "Une nouvelle page ou article SEO par mois", "Révision Search Console", "Améliorations de conversion", "Rapport de recommandations mensuel"],
      },
    ],
    addons: [
      { name: "Langue supplémentaire", price: "À partir de €250" },
      { name: "Page supplémentaire", price: "À partir de €180" },
      { name: "Téléchargement de page de projet", price: "À partir de €90/projet" },
      { name: "Google Business Profile", price: "À partir de €190" },
      { name: "Page SEO de ville", price: "À partir de €250/page" },
      { name: "Raffinement de la rédaction", price: "À partir de €350" },
    ],
  },
  work: {
    label: "Études de refonte web",
    heading: "L'architecture, recadrée pour l'écran.",
    disclaimer: "Études de refonte web montrant comment les studios d'architecture et d'intérieur peuvent présenter leur travail avec plus de clarté, de confiance et d'autorité visuelle.",
    caseStudy: {
      challenge: "Le défi.",
      approach: "La démarche.",
      outcome: "Le résultat.",
      diagnosis: "Diagnostic design.",
      diagnosisSub: "Ce qui a changé dans l'expérience — et pourquoi c'est décisif.",
      keyScreens: "Vues choisies.",
      result: "Retombées.",
    },
    items: [
      {
        slug: "villa-architecture-studio",
        title: "Site d'Architecture - Benahavís",
        location: "Benahavís, Costa del Sol",
        cardSummary: "Refonte du site, structure du portfolio, présentation mobile et parcours de contact.",
        summary: "Refonte du site, structure du portfolio, présentation mobile et parcours de contact.",
        challenge:
          "L'ancien site rendait le travail du studio difficile à comprendre, surtout sur mobile. Les projets manquaient de hiérarchie, les images semblaient déconnectées et le parcours de contact n'était pas assez clair.",
        what: "Refonte du site, structure du portfolio, présentation mobile et parcours de contact.",
        improvement:
          "Nous avons simplifié la structure, reconstruit la présentation des projets, créé une mise en page éditoriale plus forte et rendu l'expérience mobile plus fluide.",
        before: "L'ancien site rendait le portfolio du studio difficile à explorer et ne reflétait pas la qualité de ses villas.",
        after: "Nous avons créé un site éditorial plus raffiné, avec une navigation plus claire, des visuels plus forts et une présentation plus premium.",
        heroDesktop: "/images/project01/P1-thumbnail.png",
        editorialQuote: "Le site devait être aussi pensé que l'architecture elle-même.",
        diagnosisPoints: [
          { label: "Hiérarchie des projets", detail: "Un parcours plus clair de la vue d'ensemble à chaque villa, comme un portfolio curé." },
          { label: "Navigation mobile", detail: "Rythme tactile, typographie lisible et images qui tiennent sur petit écran." },
          { label: "Identité visuelle", detail: "Typographie et espacement alignés sur une présence de studio sobre et premium." },
          { label: "Contact", detail: "Moins de friction de l'intérêt à la prise de contact — intention plus nette." },
        ],
        screens: [
          { label: "Page projet", image: "/images/project01/p1-project-detail.png" },
          { label: "Expérience mobile", image: "/images/project01/p1-mobile-view.png" },
        ],
        results: [
          "Portfolio plus lisible du premier scroll à la profondeur du projet",
          "Positionnement plus premium face aux studios comparables",
          "Meilleure lisibilité mobile, où commence souvent la première visite",
          "Prise de contact plus simple lorsque le visiteur est prêt à échanger",
        ],
      },
      {
        slug: "casa-noma-marbella",
        title: "Site d'intérieur - Marbella",
        location: "Marbella, Costa del Sol",
        cardSummary:
          "Refonte du site, clarté des services, portfolio intérieur, expérience mobile et mise en place CMS.",
        summary:
          "Refonte du site, clarté des services, portfolio intérieur, expérience mobile et mise en place CMS.",
        challenge:
          "Le studio avait de beaux projets d'intérieur, mais le site paraissait trop générique. Il ne communiquait ni chaleur, ni confiance, ni la qualité des espaces.",
        what: "Refonte du site, clarté des services, portfolio intérieur, expérience mobile et mise en place CMS.",
        improvement:
          "Nous avons créé un site éditorial plus doux, centré sur l'atmosphère, la narration des projets et une découverte des services simple.",
        before:
          "L'ancien site paraissait standard et ne traduisait pas l'identité calme du studio en design d'intérieur.",
        after: "Nous avons créé un site chaleureux et élégant, proche d'un magazine d'intérieur haut de gamme.",
        heroDesktop: "/images/project02/p2-thumbnail-hero.png",
        editorialQuote: "L'intérieur est émotionnel ; le site devait porter cette confiance calme.",
        diagnosisPoints: [
          { label: "Hiérarchie des projets", detail: "Les projets se lisent comme des récits, pas comme une grille plate." },
          { label: "Navigation mobile", detail: "Rythme plus doux et images fortes sans sacrifier la performance sur téléphone." },
          { label: "Identité visuelle", detail: "Palette et rythme éditorial plus proches d'un magazine design." },
          { label: "Contact", detail: "Services et prise de contact avec intention, sans se perdre dans le bruit." },
        ],
        screens: [
          { label: "Page projet intérieur", image: "/images/project02/P2-project_details.png" },
          { label: "Expérience mobile", image: "/images/project02/P2-mobile.png" },
        ],
        results: [
          "Portfolio plus clair avec une première impression plus émotionnelle",
          "Positionnement plus premium pour des clients résidentiels exigeants",
          "Meilleure lisibilité mobile pour découvrir les projets en déplacement",
          "Prise de contact plus simple lorsque le visiteur accroche à un projet",
        ],
      },
      {
        slug: "forma-sur-malaga",
        title: "Site d'architecture - Málaga",
        location: "Málaga, Costa del Sol",
        cardSummary:
          "Refonte audacieuse, archive de projets, identité visuelle, structure mobile et CMS.",
        summary:
          "Refonte audacieuse, archive de projets, identité visuelle, structure mobile et CMS.",
        challenge:
          "Le travail du studio avait une forte personnalité architecturale, mais le site paraissait plat et oubliable. L'identité digitale ne reflétait pas l'audace des projets.",
        what: "Refonte audacieuse, archive de projets, identité visuelle, structure mobile et CMS.",
        improvement:
          "Nous avons construit un système éditorial plus tranché, avec une typographie plus affirmée, un meilleur contraste et une archive de projets plus lisible.",
        before: "L'ancien site était trop neutre et ne rendait pas le studio mémorable.",
        after: "Nous avons créé une présence visuelle plus forte, avec une navigation projet plus claire et une identité plus assurée.",
        heroDesktop: "/images/avant.png",
        editorialQuote: "Des projets audacieux méritaient une présence digitale avec le même tranchant.",
        diagnosisPoints: [
          { label: "Hiérarchie des projets", detail: "Archive et études de cas avec échelle, contraste et ordre." },
          { label: "Navigation mobile", detail: "Typographie et marges qui restent lisibles lorsque la mise en page se compresse." },
          { label: "Identité visuelle", detail: "Une voix graphique plus nette et mémorable, alignée sur le travail." },
          { label: "Contact", detail: "La prise de contact reste visible sans casser le rythme éditorial." },
        ],
        screens: [
          { label: "Archive de projets", image: "/images/redesign-preview.png" },
          { label: "Expérience mobile", image: "/images/heromock.png" },
        ],
        results: [
          "Portfolio plus clair grâce à un système typographique plus affirmé",
          "Positionnement plus premium pour des premières impressions marquantes",
          "Meilleure lisibilité mobile dans des conditions d'usage réelles",
          "Prise de contact plus simple sans diluer la voix du studio",
        ],
      },
      {
        slug: "terral-studio-estepona",
        title: "Site paysager - Estepona",
        location: "Estepona, Costa del Sol",
        cardSummary:
          "Refonte du site, portfolio outdoor, présentation des services, expérience mobile et CMS.",
        summary:
          "Refonte du site, portfolio outdoor, présentation des services, expérience mobile et CMS.",
        challenge:
          "Les projets outdoor du studio étaient visuels et émotionnels, mais le site paraissait statique. Il ne montrait pas la valeur lifestyle des terrasses, jardins et espaces extérieurs.",
        what: "Refonte du site, portfolio outdoor, présentation des services, expérience mobile et CMS.",
        improvement:
          "Nous avons créé un site plus immersif, avec des images plus grandes, des services clairs et une présentation mobile plus fluide.",
        before: "L'ancien site présentait les projets sans atmosphère ni récit fort.",
        after: "Nous avons créé une expérience portfolio plus cinématographique, centrée sur l'outdoor living et le lifestyle méditerranéen.",
        heroDesktop: "/images/apres.png",
        editorialQuote: "Le outdoor living appelait de l'atmosphère — pas une autre galerie figée.",
        diagnosisPoints: [
          { label: "Hiérarchie des projets", detail: "Le travail extérieur se lit comme des chapitres lifestyle, pas comme des photos isolées." },
          { label: "Navigation mobile", detail: "Grandes images et rythme calme qui restent fluides au chargement et au scroll." },
          { label: "Identité visuelle", detail: "Un ton cinématographique aligné sur terrasses, jardins et lumière méditerranéenne." },
          { label: "Contact", detail: "Services et prise de contact suivent naturellement, une fois le récit établi." },
        ],
        screens: [
          { label: "Page projet outdoor", image: "/images/redesign-preview.png" },
          { label: "Expérience mobile", image: "/images/heromock.png" },
        ],
        results: [
          "Portfolio plus clair avec un sens du lieu plus fort",
          "Positionnement plus premium pour un outdoor lifestyle haut de gamme",
          "Meilleure lisibilité mobile pour l'inspiration et le partage sur le terrain",
          "Prise de contact plus simple lorsque le récit convainc",
        ],
      },
    ],
  },
  audit: {
    label: "Offre d'audit gratuit",
    heading: "Vous voulez voir ce que votre site de studio pourrait devenir?",
    sub: "Envoyez votre site actuel. Je réviserai la première impression, l'expérience mobile, la clarté du portfolio, les bases SEO et le parcours de contact - et je vous enverrai un ensemble clair de recommandations.",
    what: {
      heading: "Ce que je révise",
      items: ["Première impression et crédibilité visuelle", "Expérience mobile et réactivité", "Clarté du portfolio et narration de projets", "Bases SEO et visibilité dans la recherche locale", "Parcours de demande et chemin de conversion", "Typographie, espacement et qualité d'image", "Bases de la vitesse de page", "Préparation multilingue"],
    },
    receive: {
      heading: "Ce que vous recevez",
      items: ["Audit écrit en PDF ou document", "5 à 10 recommandations prioritaires", "Notes de direction visuelle", "Capture d'écran de refonte optionnelle", "Proposition d'étape suivante claire"],
    },
    who: {
      heading: "Pour qui c'est",
      items: ["Studios d'architecture sur la Costa del Sol", "Studios de design d'intérieur à Marbella ou Estepona", "Studios préparant un relancement", "Studios avec des sites obsolètes qui perdent la confiance", "Studios ciblant des clients internationaux"],
    },
    issues: {
      heading: "Problèmes courants que je trouve",
      items: ["Page d'accueil sans hiérarchie claire", "Galerie sans contexte de projet", "Pas de mise en page optimisée pour mobile", "Zéro structure SEO local", "Typographie générique ou obsolète", "Chemin de contact manquant ou formulaire enfoui", "Pas de version multilingue pour les clients internationaux"],
    },
    form: {
      name: "Votre nom",
      studio: "Nom du studio",
      url: "URL du site actuel",
      email: "Adresse email",
      city: "Ville",
      type: "Type de studio",
      typeOptions: ["Architecture", "Design d'intérieur", "Immobilier", "Autre"],
      improve: "Qu'est-ce que vous souhaitez le plus améliorer?",
      language: "Langue préférée",
      consent: "J'accepte d'être contacté(e) au sujet de ma demande de revue de site.",
      cta: "Demander une revue du site",
      success: "Merci. Je réviserai votre site et vous contacterai dans les 48 heures.",
    },
    faq: [
      { q: "La revue du site est-elle vraiment gratuite?", a: "La première revue et les recommandations écrites sont incluses. Si vous souhaitez une refonte complète ou une implémentation, cela devient un projet payant." },
      { q: "Combien de temps cela prend-il?", a: "Je vise à envoyer la première révision dans les 48 heures. Les audits plus détaillés avec des aperçus de refonte peuvent prendre 3 à 5 jours ouvrables." },
      { q: "Dois-je m'engager à quelque chose?", a: "Pas du tout. L'audit est un livrable autonome. Si vous souhaitez continuer, nous pouvons discuter des options." },
    ],
  },
  seo: {
    label: "SEO local pour studios",
    heading: "Votre studio mérite d'être trouvé sur la Costa del Sol.",
    sub: "L'architecture et le design d'intérieur sont des métiers très locaux. Les clients internationaux cherchent avec une intention de localisation. Le SEO local fait la différence entre être trouvé et être invisible.",
    cities: [
      { name: "Marbella", desc: "L'un des marchés de luxe les plus compétitifs d'Espagne. Les studios ici ont besoin d'une forte autorité locale, d'une optimisation Google Business et d'un contenu multilingue pour capter les acheteurs internationaux de villas." },
      { name: "Estepona", desc: "Un marché en croissance pour la rénovation et la nouvelle construction architecturale. Les studios à Estepona bénéficient d'un contenu ciblé autour du boom immobilier local." },
      { name: "Benahavís", desc: "Foyer de certains des développements de villas les plus exclusifs d'Europe. Les studios d'architecture ici ont besoin de sites qui correspondent au standard premium du marché." },
      { name: "Sotogrande", desc: "Marché résidentiel et équestre haut de gamme avec une forte base d'acheteurs internationaux. La visibilité dans les recherches locales pour les anglophones et francophones est essentielle." },
      { name: "Málaga", desc: "Le hub régional avec une demande croissante de services de design d'intérieur et d'architecture. La proximité de l'aéroport en fait un point d'entrée clé pour les projets internationaux." },
      { name: "Mijas", desc: "Populaire parmi les acheteurs nordiques et britanniques. Les studios servant Mijas devraient optimiser pour la recherche multilingue et la visibilité sur Google Maps." },
      { name: "Fuengirola", desc: "Marché résidentiel dense avec un secteur actif de rénovation immobilière. Opportunité SEO rentable pour les petits studios." },
      { name: "Casares", desc: "Marché rural boutique avec des projets de villas de prestige. Le positionnement de niche et le SEO local peuvent créer une solide autorité organique." },
    ],
    sections: [
      { title: "Pourquoi le SEO local est important pour les studios d'architecture", body: "Des recherches comme 'studio d'architecture Marbella' ou 'site de design d'intérieur Estepona' ont une forte intention d'achat. Ces recherches viennent de promoteurs immobiliers, propriétaires de villas et acheteurs internationaux prêts à engager. Sans structure SEO local, votre studio est invisible exactement pour les clients que vous souhaitez." },
      { title: "Les pages de projets comme actifs SEO", body: "Chaque projet terminé est un contenu indexable. Une page de projet bien structurée avec localisation, portée, matériaux et photographie peut se positionner pour des recherches longue traîne et stimuler la découverte par des acheteurs et investisseurs immobiliers." },
      { title: "SEO multilingue", body: "Les acheteurs britanniques, allemands, français et scandinaves sont actifs sur le marché de la Costa del Sol. Un site multilingue avec une structure hreflang correcte donne à votre studio une visibilité dans des groupes linguistiques que vos concurrents ignorent probablement." },
      { title: "Google Business Profile", body: "Un Google Business Profile entièrement optimisé positionne votre studio sur Google Maps et dans les résultats de recherche locale. C'est souvent le premier point de contact pour la découverte locale et nécessite des données cohérentes de nom, d'adresse et de catégorie." },
      { title: "SEO technique", body: "La vitesse du site, les Core Web Vitals, une structure d'URL propre, les données structurées et le maillage interne affectent tous la façon dont Google voit et classe votre site. Nous nous occupons de la fondation technique pour que le contenu puisse faire son travail." },
    ],
  },
  contact: {
    label: "Revue de refonte web",
    heading: "Envoyez le site actuel.",
    sub: "S'il existe un écart clair de première impression, la prochaine étape peut être un aperçu privé de refonte. Pas de longue proposition. Pas de pitch abstrait.",
    locations: "Au service des studios à Marbella, Estepona, Benahavís, Sotogrande, Málaga, Mijas, Fuengirola, Casares, San Pedro et Nueva Andalucía.",
    response: "Réponse typique dans les 24 heures.",
    steps: [
      "Je passe en revue le site actuel - première impression, clarté du portfolio, expérience mobile et parcours de contact.",
      "J'identifie l'écart de perception le plus évident entre le travail du studio et sa présence digitale.",
      "S'il existe une opportunité claire, je réponds dans les 24 heures avec une prochaine étape concrète.",
      "Pour les studios sélectionnés, cette étape peut être un aperçu privé de refonte - déployé et prêt à juger.",
    ],
    form: {
      name: "Votre nom",
      email: "Adresse email",
      studio: "Nom du studio",
      city: "Ville",
      url: "URL du site actuel",
      type: "Type de studio",
      typeOptions: [
        "Studio d'architecture",
        "Studio de design intérieur",
        "Studio de rénovation de villas",
        "Immobilier / promoteur",
        "Autre",
      ],
      budget: "Fourchette de budget",
      budgetOptions: [
        "Pas encore décidé",
        "Moins de €1.000",
        "Environ €1.990 refonte fixe",
        "€2.000 à €4.000",
        "Soin mensuel uniquement",
      ],
      message: "Qu'est-ce qui ne fonctionne pas sur le site actuel ?",
      messagePlaceholder: "Dites-moi ce qui semble dépassé, peu clair, difficile à mettre à jour, ou pas aligné avec la qualité de votre travail.",
      cta: "Envoyer le site actuel",
      microcopy: "Sans engagement. S'il n'y a pas d'opportunité claire, je le dirai directement.",
      success: "Reçu. Je passerai en revue le site et vous répondrai dans les 24 heures.",
    },
  },
  faq: [
    { q: "Travaillez-vous avec des studios en dehors de la Costa del Sol?", a: "Notre focus est la Costa del Sol, mais nous sommes heureux de recevoir des demandes de studios ailleurs en Espagne ou de studios internationaux servant des clients espagnols." },
    { q: "Combien de temps prend une refonte de site?", a: "Une Actualisation Studio prend 1 à 2 semaines. Un Site Signature prend 3 à 5 semaines. Un projet de Studio Éditorial prend 6 à 10 semaines selon la portée et la disponibilité du contenu." },
    { q: "Dois-je fournir les textes?", a: "Nous pouvons travailler avec vos textes existants ou les raffiner. La rédaction depuis zéro est disponible en option complémentaire." },
    { q: "Et si je n'ai pas de photographie professionnelle?", a: "Nous concevons avec les photos que vous avez et conseillons sur le type d'images qui renforcerait le studio. La photographie professionnelle n'est pas nécessaire pour le lancement." },
    { q: "L'aperçu de refonte Vercel est-il gratuit?", a: "Les aperçus de refonte que je crée dans le cadre de mon processus de prospection à froid sont internes. Si vous avez reçu un lien d'aperçu et souhaitez discuter de le transformer en votre vrai site, la conversation commence là." },
    { q: "Pouvez-vous gérer le site en continu?", a: "Oui. Les plans Soin Hébergement, Soin Studio et Soin Croissance offrent un support continu à des tarifs mensuels à partir de €49." },
    { q: "Proposez-vous des sites multilingues?", a: "Oui. Nous construisons des sites en anglais, espagnol et français. Des langues supplémentaires sont disponibles en option." },
  ],
  footer: {
    tagline: "Agence de design web spécialisée pour les studios d'architecture et d'intérieur sur la Costa del Sol.",
    locations: "Marbella · Estepona · Benahavís · Sotogrande · Málaga · Mijas · Fuengirola · Casares · San Pedro · Nueva Andalucía",
    email: "hello@reframestud.io",
    whatsapp: "+34 600 000 000",
    legal: { privacy: "Politique de confidentialité", terms: "Conditions", cookies: "Cookies" },
    copy: "© 2026 REFRAME. Tous droits réservés.",
    nav: {
      sitemap: "Plan du site",
      services: "Refontes",
      pricing: "Tarifs",
      method: "Méthode",
      work: "Réalisations",
      audit: "Audit gratuit",
      seo: "SEO",
      contact: "Contact",
    },
  },
} as const;

export default fr;
